var b_txt = '';

// write the badge
	
	
/**		 	 	 	 		
	b_txt+= '<div class="flickr_badge_image" id="flickr_badge_image1"><a href="http://www.flickr.com/photos/12680330@N05/2264673489/"><img src="http://farm3.staticflickr.com/2350/2264673489_c6e7454f69_m.jpg" alt="A photo on Flickr" title="Psychedelic" height="180" width="240"></a></div>';
	
		 	 	 	 		
	b_txt+= '<div class="flickr_badge_image" id="flickr_badge_image2"><a href="http://www.flickr.com/photos/12680330@N05/2264673237/"><img src="http://farm3.staticflickr.com/2142/2264673237_0912b5a4d9_m.jpg" alt="A photo on Flickr" title="psychedelic ceiling" height="180" width="240"></a></div>';
	
		 	 	 	 		
	b_txt+= '<div class="flickr_badge_image" id="flickr_badge_image3"><a href="http://www.flickr.com/photos/johandemeijer/2400319359/"><img src="http://farm4.staticflickr.com/3238/2400319359_9f804f663c_m.jpg" alt="A photo on Flickr" title="Tabletennistabletennistabletennistable" height="240" width="180"></a></div>';
	
		 	 	 	 		
	b_txt+= '<div class="flickr_badge_image" id="flickr_badge_image4"><a href="http://www.flickr.com/photos/ricksu/2392972462/"><img src="http://farm3.staticflickr.com/2268/2392972462_51cd64e180_m.jpg" alt="A photo on Flickr" title="Mireille wat doe je nou! ;)" height="180" width="240"></a></div>';
	
		 	 	 	 		
	b_txt+= '<div class="flickr_badge_image" id="flickr_badge_image5"><a href="http://www.flickr.com/photos/pplaggenborg/4197692164/"><img src="http://farm3.staticflickr.com/2549/4197692164_ffd7f74abb_m.jpg" alt="A photo on Flickr" title="LBi Gouden Prikkel Awards 2009" height="160" width="240"></a></div>';
	
		 	 	 	 		
	b_txt+= '<div class="flickr_badge_image" id="flickr_badge_image6"><a href="http://www.flickr.com/photos/waarvandaan/2398448628/"><img src="http://farm3.staticflickr.com/2310/2398448628_52a3e701a5_m.jpg" alt="A photo on Flickr" title="Spin Awards Bureau Battle" height="180" width="240"></a></div>';
	
		 	 	 	 		
	b_txt+= '<div class="flickr_badge_image" id="flickr_badge_image7"><a href="http://www.flickr.com/photos/stijnbokhove/2380255917/"><img src="http://farm4.staticflickr.com/3029/2380255917_e7c0858f94_m.jpg" alt="A photo on Flickr" title="Wintersport 2008 Lost Boys" height="180" width="240"></a></div>';
	
		 	 	 	 		
	b_txt+= '<div class="flickr_badge_image" id="flickr_badge_image8"><a href="http://www.flickr.com/photos/stijnbokhove/2628677176/"><img src="http://farm4.staticflickr.com/3279/2628677176_a89a53024c_m.jpg" alt="A photo on Flickr" title="01072008" height="180" width="240"></a></div>';
	
		 	 	 	 		
	b_txt+= '<div class="flickr_badge_image" id="flickr_badge_image9"><a href="http://www.flickr.com/photos/stijnbokhove/2380269059/"><img src="http://farm4.staticflickr.com/3010/2380269059_b25e2314d8_m.jpg" alt="A photo on Flickr" title="Wintersport 2008 Lost Boys" height="240" width="180"></a></div>';
	
		 	 	 	 		
	b_txt+= '<div class="flickr_badge_image" id="flickr_badge_image10"><a href="http://www.flickr.com/photos/stijnbokhove/1770081997/"><img src="http://farm3.staticflickr.com/2327/1770081997_f0cb4c6bca_m.jpg" alt="A photo on Flickr" title="DSC01093.JPG" height="180" width="240"></a></div>';
*/

b_txt += '<span style="position:absolute;left:-999em;top:-999em;visibility:hidden" class="flickr_badge_beacon"><img src="http://geo.yahoo.com/p?s=792600102&t=cafbdb9cc33b7ee1f709f90aafd2df94&r=http%3A%2F%2Fwww.flickr.com%2F&fl_ev=0&lang=en&intl=us" width="0" height="0" alt="" /></span>';

document.write(b_txt);